### ISSUE TITLE
tester.py doesn't work on ECF (No such file or directory: 'sh ./run')

### ISSUE THREAD

**Issue by zhuowei** [utek-2018/competition-package#7]
Running the latest tester on ECF fails:

```
[user@p11 ~/utek-2018]$ python3 tester.py
cp: `./input/1a.in' and `input/1a.in' are the same file
cp: `./input/1b.in' and `input/1b.in' are the same file
cp: `./input/1c.in' and `input/1c.in' are the same file
cp: `./input/2a.in' and `input/2a.in' are the same file
cp: `./input/2b.in' and `input/2b.in' are the same file
cp: `./input/3a.in' and `input/3a.in' are the same file
cp: `./input/3b.in' and `input/3b.in' are the same file
cp: `./input/3c.in' and `input/3c.in' are the same file
cp: `./input/3d.in' and `input/3d.in' are the same file
cp: `./input/5a.in' and `input/5a.in' are the same file
Traceback (most recent call last):
  File "tester.py", line 40, in <module>
    subprocess.call('sh ./run', timeout=5*60)
  File "/local/packages/python3/lib/python3.3/subprocess.py", line 520, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/local/packages/python3/lib/python3.3/subprocess.py", line 820, in __init__
    restore_signals, start_new_session)
  File "/local/packages/python3/lib/python3.3/subprocess.py", line 1438, in _execute_child
    raise child_exception_type(errno_num, err_msg)
FileNotFoundError: [Errno 2] No such file or directory: 'sh ./run'
[user@p11 ~/utek-2018]$
```

**Comment by c2huc2hu** [comment]
Did you create a run script? Can you `ls` in the same directory?

**Comment by zhuowei** [comment]
@c2huc2hu 
```
[user@p11 ~/utek-2018]$ ls -l run
-rwx------ 1 user esc2T1 259 Jan 13 14:39 run
```

This fixes it:

```
diff --git a/tester.py b/tester.py
index d538f5c..563064f 100644
--- a/tester.py
+++ b/tester.py
@@ -37,7 +37,7 @@ t = time.time()
 # use this to suppress stdout and stderr
 # with open(output_path + '/stdout.txt', 'w') as stdout, open(output_path + '/stderr.txt', 'w') as stderr:
 #     subprocess.call('sh ./run', stdout=stdout, stderr=stderr, timeout=10*60)   # add the executable name for Git bash (sh ./run for the exampl
-subprocess.call('sh ./run', timeout=5*60)
+subprocess.call(['sh', './run'], timeout=5*60)
 print('Took {} seconds'.format(time.time() - t))

 os.makedirs('ref', exist_ok=True)
```

**Comment by c2huc2hu** [comment]
okay. taking out `sh` might work too

**Comment by zhuowei** [comment]
@c2huc2hu For your fix: `run` doesn't have executable perm set in your repo; might want to do a chmod +x
